### ISSUE TITLE
Common class name conflicts

### ISSUE THREAD

**Issue by kyle-williams-1** [Katello/puppet-common#29]
The **common** class name easily conflicts with many other base class names on the Puppet Forge. This makes dependency management difficult, and sometimes impossible.

Since this appears to be grouped with a series of modules used with Katello and Foreman, it would be nice to see a base class name that doesn't easily conflict.

I'm happy to do the PR for this, but I'd like to know first if it's something that would be considered. Thanks!

**Comment by ekohl** [comment]
We actually got rid of this module *very* recently (https://github.com/Katello/katello-installer/commit/c2ec441589495089393134c3d80573adce62c2db) so our intent is to archive it. Doing a rename would be a wasted effort. We do need to complete the effort which will be done probably be done when we release updated modules. This module has been a target on my kill list for quite some time, partly because of the reason you mentioned.

Because of that I'm going to close this issue now.

**Comment by kyle-williams-1** [comment]
Thanks @ekohl
